name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clean Gradle Cache
        run: rm -rf ~/.gradle/wrapper/dists ~/.gradle/caches/

      - name: Force Gradle Version 8.1.1
        run: ./gradlew wrapper --gradle-version 8.1.1

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build APK with Debug Log
        run: ./gradlew assembleDebug --stacktrace --info

      - name: List Output Files
        run: find app/build/ -type f

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/**/*.apk
